language: python
python:
  - "3.6"
  - "3.7"

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m unittest -v tests

jobs:
  include:
    - stage: genretating documentaion
      install:
        - pip install -r requirements.txt
        - pip install sphinx sphinx-rtd-theme
      script:
        - cd docs; make html
      deploy:
        provider: pages
        local_dir: docs/_build/html
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master